### ISSUE TITLE
could you add gap config by monitor?

### ISSUE THREAD

**Issue by omg-urt** [xhsdf/rtile#6]
Something like this.
`<gaps monitor="VGA-1" top="0" bottom="16" left="0" right="0" windows_x="0" windows_y="0"/> `
`<gaps monitor="LVDS-1" top="0" bottom="0" left="0" right="0" windows_x="0" windows_y="0"/>`

**Comment by xhsdf** [comment]
https://pastebin.com/pYgtQ50E
Does this work for you?

Config in your case would be
```
<gaps monitor="VGA-1" bottom="16"/>
<gaps top="0" bottom="0" left="0" right="0" windows_x="0" windows_y="0"/>
```

**Comment by omg-urt** [comment]
Nop, it applies bottom 0 to vga also.

**Comment by xhsdf** [comment]
Weird, it's working for me. Which commands are you testing? Does --version show `2.03-test`?

**Comment by omg-urt** [comment]
ahh sry, i need to use that pastebin version no?

**Comment by xhsdf** [comment]
Yes

**Comment by omg-urt** [comment]
Ok working with that pastebin version.
Terminals sometimes i need to do rtile --all-active 2 times to get fullscreen but that maybe is another issue.

**Comment by xhsdf** [comment]
Nice, I just pushed the changes to the repository.
