### ISSUE TITLE
Unexpected error

### ISSUE THREAD

**Issue by vredesbyyrd** [xhsdf/rtile#7]
Hi, thanks for sharing this script - its appears to be just what I was looking for. 

Running something basic, eg `rtile tl` results in nothing happening. Actually, none of commands work. Closest I could get to a useful error was running: `pxdo.py --print-window-info`

`Unexpected error: <class 'TypeError'>` 

I am running this on arch linux in 2bwm, although I see the same result in budgie. 

If you have any thoughts on what the issue could be I am all ears! Thanks for your time.

**Comment by xhsdf** [comment]
Hello, I have no idea what could cause this. What Python version do you use?
What is the output if you remove lines 23, 39 and 40 from pxdo.py?

Or just use `pxdo.py --print-window-info --debug` on the version I just updated

**Comment by vredesbyyrd** [comment]
Thanks much for the quick response. 

Python version is 3.10

After commenting out the referenced lines and running either `pxdo.py --print-window-info` or `rtile tl` the following error is returned.  

```zsh
Traceback (most recent call last):
  File "/home/clu/.python/bin/pxdo.py", line 223, in <module>
    main(argv[1:])
  File "/home/clu/.python/bin/pxdo.py", line 31, in main
    print_window_info()
  File "/home/clu/.python/bin/pxdo.py", line 49, in print_window_info
    for w in Window.get_windows():
  File "/home/clu/.python/bin/pxdo.py", line 141, in get_windows
    if display.intern_atom("_NET_WM_ACTION_MOVE") in w.allowed_actions or display.intern_atom("_NET_WM_ACTION_RESIZE") in w.allowed_actions:
TypeError: argument of type 'NoneType' is not iterable
```

**Comment by xhsdf** [comment]
Does this work?
https://pastebin.com/wQzFP9Jg

**Comment by vredesbyyrd** [comment]
Okay just tried the pastebin code. On `2bwm` the same commands fail silently. On `Budgie` it fails with: 

```shell
Traceback (most recent call last):
  File "/home/clu/.python/bin/pxdo.py", line 226, in <module>
    main(argv[1:])
  File "/home/clu/.python/bin/pxdo.py", line 31, in main
    print_window_info()
  File "/home/clu/.python/bin/pxdo.py", line 52, in print_window_info
    for w in Window.get_windows():
  File "/home/clu/.python/bin/pxdo.py", line 141, in get_windows
    w = Window.from_id(int(id))
  File "/home/clu/.python/bin/pxdo.py", line 153, in from_id
    return Window(display.create_resource_object('window', wid), wid, full)
  File "/home/clu/.python/bin/pxdo.py", line 118, in __init__
    self.workspace = int(self.get_property('_NET_WM_DESKTOP')[0])
TypeError: 'NoneType' object is not subscriptable
```

`2bwm` uses `xcb` as opposed to `xlib`, so that could be an issue? Although I use many `xdotool`, `wmctrl` scripts without issue. I have no idea why `budgie` would not work.

**Comment by vredesbyyrd** [comment]
Well this might explain it on `2bwm` - `_NET_WM_ALLOWED_ACTIONS(ATOM)` is not listed at all when running `xprop` on a window. That atom must not be implemented in `2bwm`. Does not explain `budgie` though, as it has the required `_NET_WM_ACTION_RESIZE` and `_NET_WM_ACTION_MOVE`

**Comment by xhsdf** [comment]
What is your complete `xprop` output on a random window?

**Comment by vredesbyyrd** [comment]
`tilda terminal` window on `2bwm`   EDIT: formatting

```
_NET_WM_ICON_GEOMETRY(CARDINAL) = 277, 1059, 234, 21
_NET_WM_STATE(_NET_WM_STATE) = 0x1, 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x3000007
		bitmap id # of mask for icon: 0x3000012
		window id # of group leader: 0x3000001
_GTK_THEME_VARIANT(UTF8_STRING) = 
_NET_WM_USER_TIME(CARDINAL) = 11415886
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) = 	Icon (48 x 48):
_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 50331653, 50331654
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x3000004
WM_CLIENT_LEADER(WINDOW): window id # 0x3000001
_NET_WM_PID(CARDINAL) = 407380
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "archlinux"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 27 by 23
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "tilda", "Tilda"
WM_ICON_NAME(STRING) = "xprop:~"
_NET_WM_ICON_NAME(UTF8_STRING) = "xprop:~"
WM_NAME(STRING) = "xprop:~"
_NET_WM_NAME(UTF8_STRING) = "xprop:~"

```

**Comment by vredesbyyrd** [comment]
`tilda terminal` window on `budgie` .  

```
_NET_WM_ICON_GEOMETRY(CARDINAL) = 277, 1059, 234, 21
_NET_WM_STATE(ATOM) = _NET_WM_STATE_FOCUSED
WM_STATE(WM_STATE):
		window state: Normal
		icon window: 0x0
_NET_WM_DESKTOP(CARDINAL) = 0
_GTK_EDGE_CONSTRAINTS(CARDINAL) = 170
_NET_WM_ALLOWED_ACTIONS(ATOM) = _NET_WM_ACTION_MOVE, _NET_WM_ACTION_RESIZE, _NET_WM_ACTION_FULLSCREEN, _NET_WM_ACTION_MINIMIZE, _NET_WM_ACTION_MAXIMIZE_HORZ, _NET_WM_ACTION_MAXIMIZE_VERT, _NET_WM_ACTION_CHANGE_DESKTOP, _NET_WM_ACTION_CLOSE, _NET_WM_ACTION_ABOVE, _NET_WM_ACTION_BELOW
WM_HINTS(WM_HINTS):
		Client accepts input or input focus: True
		Initial state is Normal State.
		bitmap id # to use for icon: 0x3a00007
		bitmap id # of mask for icon: 0x3a00012
		window id # of group leader: 0x3a00001
_GTK_THEME_VARIANT(UTF8_STRING) = 
XdndAware(ATOM) = BITMAP
_NET_WM_ICON(CARDINAL) = 	Icon (48 x 48):

_MOTIF_WM_HINTS(_MOTIF_WM_HINTS) = 0x2, 0x0, 0x0, 0x0, 0x0
_NET_WM_WINDOW_TYPE(ATOM) = _NET_WM_WINDOW_TYPE_NORMAL
_NET_WM_SYNC_REQUEST_COUNTER(CARDINAL) = 60817413, 60817414
_NET_WM_USER_TIME_WINDOW(WINDOW): window id # 0x3a00004
WM_CLIENT_LEADER(WINDOW): window id # 0x3a00001
_NET_WM_PID(CARDINAL) = 566851
WM_LOCALE_NAME(STRING) = "en_US.UTF-8"
WM_CLIENT_MACHINE(STRING) = "archlinux"
WM_NORMAL_HINTS(WM_SIZE_HINTS):
		program specified minimum size: 27 by 23
		program specified base size: 0 by 0
		window gravity: NorthWest
WM_PROTOCOLS(ATOM): protocols  WM_DELETE_WINDOW, WM_TAKE_FOCUS, _NET_WM_PING, _NET_WM_SYNC_REQUEST
WM_CLASS(STRING) = "tilda", "Tilda"
WM_ICON_NAME(STRING) = "xprop:~"
_NET_WM_ICON_NAME(UTF8_STRING) = "xprop:~"
WM_NAME(STRING) = "xprop:~"
_NET_WM_NAME(UTF8_STRING) = "xprop:~"
```

**Comment by xhsdf** [comment]
It's weird that it fails on `_NET_WM_DESKTOP` now when that information is correct.
This could work on 2bwm now: https://pastebin.com/wpgFsWsm
But it can't check if the windows are supposed to be moved or not...

**Comment by vredesbyyrd** [comment]
> It's weird that it fails on _NET_WM_DESKTOP now when that information is correct. 

Agreed. 

`pxdo.py --print-window-info --debug ` works on `2bwm`  

```
WINDOW: 0x3000003	3840x1200+0+0	0,0,0,0	0:0	,active,	Tilda	pxdo.py --print-window-in...
WINDOW: 0x600008	3840x1200+0+0	0,0,0,0	2:0	,	Howl	Howl
WINDOW: 0x2400008	3840x1200+0+0	0,0,0,0	3:0	,	Mpdevil	The Fall and Rise of Elliot Brown  Blackalicious
WINDOW: 0x2c0002c	3840x1200+0+0	0,0,0,0	0:0	,	firefoxdeveloperedition	#!/usr/bin/pythonNAME = "pxdo"VERSION = "0.12d"from sys import exc - Pastebin.com  Firefox Developer Edition
```

But oddly `rtile` still fails. I tried binding `rtile` to keybinds, just to be sure it was not a `tilda` window thing: 

```
# teleport window to corner
super + {slash,period,semicolon,apostrophe}
	/usr/bin/rtile {"br","bl","tl","tr"}
```

But rtile fails silently. Strange indeed. 

I would say do not wreck your brain too hard over it - on my behalf anyway. The main thing I want is "quarter snapping" the _active_ window, which I should be able to accomplish fairly easily with a `xdotool / wmctrl` script. Although I'd really like gaps, lol. So i'd have to think on how to calculate gaps per screen size etc. 

Much appreciate your help though.

**Comment by xhsdf** [comment]
Does https://pastebin.com/ttyGUjeL also work?
And what happens if you comment in line 75 of `rtile.rb`?
Also replace line 74 with `command = "pxdo.py " + $actions.join(" ") + " --debug"`

**Comment by vredesbyyrd** [comment]
That pastebin also works. 

Apologies -  I do know `ruby` whatsoever. Should line 75 just be: `puts command`? 

Doing that and the addition on line 74 returns:  

`pxdo.py --move-0x3000003-927x497+22+42 --debug` 

So it appears like it _should_ be working, the window just does not tile though.

**Comment by xhsdf** [comment]
Does anything happen if you put `pxdo.py --move-0x3000003-927x497+22+42 --debug` into the console?

**Comment by vredesbyyrd** [comment]
Nope :/

**Comment by xhsdf** [comment]
Then I don't think there is anything I can do. Looks like the XLib commands get ignored. Sorry. This is only tested on Openbox.

**Comment by vredesbyyrd** [comment]
No sweat - I much appreciate the help! I will hop into budgie just to check that any of the changes helped anything there.  I'll report back if they did.

I'll try and write a little script for quarter snapping with `xdotool / wmctrl`, its all I really want anyway. 

If I ever switch to something like openbox ill give your program another go, it looks great! Thanks again.

**Comment by xhsdf** [comment]
You could try https://github.com/xhsdf/rtile/blob/6357f531476a61631c102076dd91c5d751f0b8b9/rtile.rb
It used xprop, wmctrl, xwininfo and xrandr.
But I stopped using them because they had bugs

**Comment by vredesbyyrd** [comment]
I'll give that version a go, thanks.  

And just for completeness sake - running `pxdo.py --move-0x3000003-927x497+22+42 --debug` on a budgie window returns:  

```
Traceback (most recent call last):
  File "/home/clu/.python/bin/pxdo.py", line 229, in <module>
    main(argv[1:])
  File "/home/clu/.python/bin/pxdo.py", line 37, in main
    w = Window.from_id(int(wid, 16), False)
  File "/home/clu/.python/bin/pxdo.py", line 156, in from_id
    return Window(display.create_resource_object('window', wid), wid, full)
  File "/home/clu/.python/bin/pxdo.py", line 109, in __init__
    extents = self.get_property('_NET_FRAME_EXTENTS')
  File "/home/clu/.python/bin/pxdo.py", line 192, in get_property
    atom = self.win.get_full_property(display.intern_atom(prop), AnyPropertyType)
  File "/usr/lib/python3.10/site-packages/Xlib/xobject/drawable.py", line 472, in get_full_property
    prop = self.get_property(property, property_type, 0, sizehint)
  File "/usr/lib/python3.10/site-packages/Xlib/xobject/drawable.py", line 455, in get_property
    r = request.GetProperty(display = self.display,
  File "/usr/lib/python3.10/site-packages/Xlib/protocol/rq.py", line 1369, in __init__
    self.reply()
  File "/usr/lib/python3.10/site-packages/Xlib/protocol/rq.py", line 1389, in reply
    raise self._error
Xlib.error.BadWindow: <class 'Xlib.error.BadWindow'>: code = 3, resource_id = <Resource 0x03000003>, sequence_number = 17, major_opcode = 20, minor_opcode = 0
```

**Comment by xhsdf** [comment]
> And just for completeness sake - running `pxdo.py --move-0x3000003-927x497+22+42 --debug` on a budgie window returns:

`0x3000003` is the window id from your previous 2bwm session. You would need to get a need command from rtile first

**Comment by vredesbyyrd** [comment]
lol, duh.
